### ISSUE TITLE
dp口点不亮

### ISSUE THREAD

**Issue by mysaber** [daliansky/SoarSea-S210H-Hackintosh#1]
一样的机器，就是cpu是i7 10870h，好奇怪那个dp口点不亮，安装或者装完进去，都是在苹果logo那里闪一下就没了，hdmi口闪一下找不到信号源，马上又可以了

**Comment by mysaber** [comment]
捣鼓了半天，原来dp口不能转换，转换就不行，不转换可以

**Comment by daliansky** [comment]
如果想DP转HDMI的话，是需要选购主动式的线才行
